import { GoogleGenAI, Type } from "@google/genai";
import { Category, Skill, Goal } from "../types";

const getAI = (customKey?: string) => {
  const key = customKey || process.env.GEMINI_API_KEY;
  if (!key) throw new Error("API_KEY_MISSING: No Gemini API key found. Please provide a custom API key in Settings.");
  return new GoogleGenAI({ apiKey: key });
};

export const generateQuests = async (skill: Skill, categoryName: string, existingQuests?: Goal[], customApiKey?: string): Promise<Partial<Goal>[]> => {
  try {
    const ai = getAI(customApiKey);
    const questContext = existingQuests && existingQuests.length > 0 
      ? `The user has already completed or is working on these quests: ${existingQuests.map(g => g.title).join(", ")}. Generate the NEXT logical progressive quests.`
      : "This is the start of the skill path. Generate the first 3 progressive quests.";

    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Generate 3 progressive "quests" (goals) for a life-RPG app for the skill "${skill.name}" in the "${categoryName}" category. 
      Skill Description: "${skill.description}"
      The current skill level is ${skill.level}. 
      ${questContext}
      
      Requirements:
      1. Use SIMPLE, EVERYDAY language. Avoid complex or academic words. 
      2. Progression: The quests should follow a sequence from simple to hard, improvising one aspect of the skill at a time based on mastery fundamentals.
      3. Include an "achieveGuide" for each quest explaining HOW to achieve it in 3 simple, actionable steps.
      4. Mark some quests as "isRepeatable" (boolean) if they are daily habits.
      5. Avoid mentioning that this content is generated by AI.
      6. Assign a "difficulty" of "trivial", "easy", "medium", or "hard".
      7. Return the result as a JSON array of objects with "title", "difficulty", "achieveGuide", and "isRepeatable".`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              title: { type: Type.STRING, description: "A short, catchy quest title." },
              difficulty: { type: Type.STRING, enum: ['trivial', 'easy', 'medium', 'hard'] },
              achieveGuide: { type: Type.STRING, description: "Brief guide on how to achieve this quest." },
              isRepeatable: { type: Type.BOOLEAN, description: "Whether this quest can be repeated daily." }
            },
            required: ["title", "difficulty", "achieveGuide", "isRepeatable"]
          }
        }
      }
    });

    return JSON.parse(response.text.trim());
  } catch (error) {
    console.error("Gemini API Error (generateQuests):", error);
    throw error;
  }
};

export const generateRandomQuestPack = async (skills: {skill: Skill, categoryName: string}[], existingQuests: Goal[], customApiKey?: string): Promise<{skillId: string, quest: Partial<Goal>}[]> => {
  try {
    const ai = getAI(customApiKey);
    const skillsContext = skills.map(s => `Skill: "${s.skill.name}" (Level ${s.skill.level}, Description: "${s.skill.description}") in Category: "${s.categoryName}"`).join("\n");
    
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Generate exactly one unique "quest" (goal) for each of the following skills in a life-RPG app:
      ${skillsContext}
      
      Requirements for each quest:
      1. Use SIMPLE, EVERYDAY language.
      2. Progression: The quest should be appropriate for the current skill level.
      3. Include an "achieveGuide" explaining HOW to achieve it in 3 simple, actionable steps.
      4. Mark as "isRepeatable" (boolean) if it's a daily habit.
      5. Avoid mentioning AI.
      6. Assign a "difficulty" of "trivial", "easy", "medium", or "hard".
      7. Return the result as a JSON array of objects, where each object has "skillId" (matching the input skill's ID) and "quest" (an object with "title", "difficulty", "achieveGuide", and "isRepeatable").`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              skillId: { type: Type.STRING, description: "The ID of the skill this quest belongs to." },
              quest: {
                type: Type.OBJECT,
                properties: {
                  title: { type: Type.STRING },
                  difficulty: { type: Type.STRING, enum: ['trivial', 'easy', 'medium', 'hard'] },
                  achieveGuide: { type: Type.STRING },
                  isRepeatable: { type: Type.BOOLEAN }
                },
                required: ["title", "difficulty", "achieveGuide", "isRepeatable"]
              }
            },
            required: ["skillId", "quest"]
          }
        }
      }
    });

    return JSON.parse(response.text.trim());
  } catch (error) {
    console.error("Gemini API Error (generateRandomQuestPack):", error);
    throw error;
  }
};

export const suggestSkills = async (category: Category, customApiKey?: string): Promise<Partial<Skill>[]> => {
  try {
    const ai = getAI(customApiKey);
    const existingSkills = category.skills.map(s => s.name).join(", ");
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Suggest 3 new skills to add to the "${category.name}" category in a life-RPG app.
      Existing skills in this category: ${existingSkills}.
      The new skills should complement the existing ones and follow a logical progression.
      Avoid mentioning that this content is generated by AI.
      Return the result as a JSON array of objects with "name", "description", and "xpReward" (initial reward for quests, between 30 and 80).`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING, description: "Name of the skill." },
              description: { type: Type.STRING, description: "A brief description of what the skill represents." },
              xpReward: { type: Type.NUMBER, description: "Initial XP reward for quests of this skill." }
            },
            required: ["name", "description", "xpReward"]
          }
        }
      }
    });

    return JSON.parse(response.text.trim());
  } catch (error) {
    console.error("Gemini API Error (suggestSkills):", error);
    throw error;
  }
};

export const getSkillGuide = async (skill: Skill, categoryName: string, currentQuests?: Goal[], customApiKey?: string): Promise<string> => {
  try {
    const ai = getAI(customApiKey);
    const questContext = currentQuests && currentQuests.length > 0
      ? `The user is currently working on these specific quests: ${currentQuests.map(g => g.title).join(", ")}. Provide knowledge and tips specifically related to achieving these quests.`
      : "Provide general mastery knowledge for this skill level.";

    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Provide an informative and practical "Mastery Guide" for the skill "${skill.name}" in the "${categoryName}" category.
      Skill Description: "${skill.description}"
      The user is currently at Level ${skill.level}. 
      ${questContext}
      
      Requirements:
      1. Use SIMPLE, EVERYDAY language. Avoid complex, academic, or "big" words like "somatic", "fiscal", or "steadfastness".
      2. Tone: Professional, educational, and practical. Avoid "RPG" or "gamified" talk.
      3. Content: 
         - Provide 3 specific **actionable tips** for immediate improvement, tailored to the current quests if provided.
         - Explain the core concepts needed to succeed in the current stage of the skill path.
         - Mention how these concepts bridge the gap to the next level of mastery.
      4. Progression: Since the user is at Level ${skill.level}, provide concepts appropriate for this stage. 
      5. Format: Use Markdown for formatting. Use bold for key terms.
      6. Length: Keep it concise but valuable (approx 150-200 words).
      7. Avoid mentioning that this content is generated by AI.`,
    });

    return response.text.trim();
  } catch (error) {
    console.error("Gemini API Error (getSkillGuide):", error);
    throw error;
  }
};

export const getQuestTip = async (questTitle: string, skillName: string, customApiKey?: string): Promise<string> => {
  try {
    const ai = getAI(customApiKey);
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Provide a 3-step actionable guide on how to achieve the quest "${questTitle}" for the skill "${skillName}". 
      Keep it very concise and practical. 
      Use SIMPLE, EVERYDAY language. Avoid complex words.
      Avoid mentioning that this content is generated by AI.`,
    });
    return response.text.trim();
  } catch (error) {
    console.error("Gemini API Error (getQuestTip):", error);
    throw error;
  }
};

export const getCategoryConsistencyName = async (categoryName: string, customApiKey?: string): Promise<string> => {
  try {
    const ai = getAI(customApiKey);
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Generate a creative and professional "Consistency/Reliability" name for the category "${categoryName}" in a life-RPG app. 
      Use SIMPLE, EVERYDAY language. Avoid complex or "big" words like "somatic", "fiscal", "steadfastness", or "discipline".
      For example, for "Money Management", it could be "Money Habits" or "Spending Control". 
      For "Physical", it could be "Daily Exercise" or "Body Routine".
      Avoid mentioning that this content is generated by AI.
      Return only the name, no extra text.`,
    });
    return response.text.trim() || `${categoryName} Habits`;
  } catch (error) {
    console.error("Gemini API Error (getCategoryConsistencyName):", error);
    throw error;
  }
};

export const getMockingMessage = async (userStats: any, goals: Goal[], categories: Category[], customApiKey?: string): Promise<string> => {
  try {
    const ai = getAI(customApiKey);
    const completedCount = goals.filter(g => g.completed).length;
    const totalCount = goals.length;
    const skills = categories.flatMap(c => c.skills).filter(s => s.isUnlocked).map(s => s.name).join(", ");
    
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Generate a humorous one-liner for a life-RPG app that provides "witty encouragement". 
      The tone should be "playful banter" - funny, slightly sarcastic, but ultimately supportive and never mean-spirited.
      Avoid mentioning that this content is generated by AI.
      Context:
      - Level: ${userStats.level}
      - Quests completed: ${completedCount}/${totalCount}
      - Skills learning: ${skills}
      
      Guidelines:
      - Use humor and wit rather than direct insults.
      - Avoid aggressive words like "failure", "loser", or "pig".
      - Focus on the absurdity of the "grind" or lighthearted observations about their progress.
      
      Examples:
      - "Your 'Gym' skill is currently at 'Thinking about it' level. Let's move it to 'Actually there'?"
      - "Level ${userStats.level}? You're basically a legendary hero... in training... very early training."
      - "Learning Financial Management? Your wallet just sent me a thank you note."
      - "If procrastination was a skill, you'd be Level 100 by now. Let's work on the others?"
      
      Return only the one-liner, no extra text. Keep it short, funny, and punchy.`,
    });
    return response.text.trim() || "One step at a time. Even a snail gets to the finish line eventually.";
  } catch (error) {
    console.error("Gemini API Error (getMockingMessage):", error);
    throw error;
  }
};

export const isRateLimitError = (error: any): boolean => {
  if (!error) return false;
  
  // Check status codes
  const status = error.status || error.statusCode || error.response?.status;
  if (status === 429) return true;

  // Check message content
  const message = (error.message || "").toLowerCase();
  const stack = (error.stack || "").toLowerCase();
  
  const rateLimitKeywords = [
    '429', 
    'quota', 
    'rate limit', 
    'exhausted', 
    'resource_exhausted',
    'too many requests',
    'limit reached'
  ];

  return rateLimitKeywords.some(keyword => message.includes(keyword) || stack.includes(keyword));
};

export const getGeminiErrorMessage = (error: any): string => {
  if (!error) return "An unknown error occurred.";
  
  const message = (error.message || "").toLowerCase();
  const status = error.status || error.statusCode || error.response?.status;

  if (status === 401 || status === 403 || message.includes('api_key_invalid') || message.includes('invalid api key')) {
    return "Invalid API Key. Please check your settings in Google AI Studio.";
  }

  if (message.includes('api_key_missing')) {
    return "AI API Key is missing. Please add your own key in Settings to use AI features.";
  }

  if (isRateLimitError(error)) {
    if (message.includes('quota') || message.includes('exhausted')) {
      return "Daily AI quota reached. Please try again later or use your own API key.";
    }
    return "AI is busy. Please wait a moment before trying again.";
  }

  if (message.includes('fetch') || message.includes('network') || message.includes('offline')) {
    return "Network error. Please check your internet connection.";
  }

  return error.message || "Failed to connect to AI service.";
};
