export interface FinanceCategoryMeta {
  id: string;
  name: string;
  color: string;
}

export const EXPENSE_CATEGORY_META: FinanceCategoryMeta[] = [
  { id: 'food', name: 'Food/Dining', color: '#f87171' },
  { id: 'groceries', name: 'Groceries', color: '#fca5a5' },
  { id: 'rent', name: 'Rent/Housing', color: '#60a5fa' },
  { id: 'electricity', name: 'Electricity Bill', color: '#fbbf24' },
  { id: 'water', name: 'Water Bill', color: '#3b82f6' },
  { id: 'gas', name: 'Gas Bill', color: '#f97316' },
  { id: 'internet', name: 'Internet/Wi-Fi', color: '#10b981' },
  { id: 'phone', name: 'Phone Bill', color: '#84cc16' },
  { id: 'fuel', name: 'Fuel/Petrol', color: '#eab308' },
  { id: 'public_transit', name: 'Public Transport', color: '#ec4899' },
  { id: 'cabs', name: 'Cabs/Taxi', color: '#f59e0b' },
  { id: 'car_maint', name: 'Vehicle Maintenance', color: '#64748b' },
  { id: 'medicine', name: 'Medicines', color: '#ef4444' },
  { id: 'doctor', name: 'Doctor/Health', color: '#14b8a6' },
  { id: 'gym', name: 'Gym/Fitness', color: '#10b981' },
  { id: 'cinema', name: 'Movies/Cinema', color: '#d946ef' },
  { id: 'gaming', name: 'Video Games', color: '#6366f1' },
  { id: 'books', name: 'Books/Courses', color: '#a855f7' },
  { id: 'clothing', name: 'Clothing', color: '#f43f5e' },
  { id: 'salon', name: 'Salon/Haircut', color: '#06b6d4' },
  { id: 'pets', name: 'Pets', color: '#f97316' },
  { id: 'electronics', name: 'Electronics/Gadgets', color: '#3b82f6' },
  { id: 'furniture', name: 'Furniture/Decor', color: '#b45309' },
  { id: 'stationery', name: 'Stationery', color: '#65a30d' },
  { id: 'gifts', name: 'Gifts given', color: '#ec4899' },
  { id: 'charity', name: 'Charity/Donating', color: '#ef4444' },
  { id: 'travel', name: 'Travel/Flights', color: '#06b6d4' },
  { id: 'hotel', name: 'Hotel/Stay', color: '#4d7c0f' },
  { id: 'cafe', name: 'Café/Coffee-shops', color: '#b45309' },
  { id: 'snacks', name: 'Snacks/Fastfood', color: '#eab308' },
  { id: 'bars', name: 'Bars/Alcohol', color: '#a21caf' },
  { id: 'taxes', name: 'Taxes paid', color: '#b91c1c' },
  { id: 'bank_fees', name: 'Bank Charges/Fees', color: '#475569' },
  { id: 'subscriptions', name: 'Subscriptions', color: '#a855f7' },
  { id: 'epf_contribution', name: 'EPF Deduction', color: '#047857' },
  { id: 'repairs', name: 'Home Repairs', color: '#d97706' },
  { id: 'cleaning', name: 'Laundry/Cleaning', color: '#06b6d4' },
  { id: 'insurance', name: 'Insurance Premium', color: '#0369a1' },
  { id: 'penalty', name: 'Fines/Penalties', color: '#dc2626' },
  { id: 'invest_outflow', name: 'Investment out', color: '#059669' },
  { id: 'bike_maint', name: 'Bike Expense', color: '#4f46e5' },
  { id: 'car_expense', name: 'Car Expense', color: '#ec4899' },
  { id: 'loan_emi', name: 'Loan EMI/Interest', color: '#991b1b' },
  { id: 'office_lunch', name: 'Office Lunch/Canteen', color: '#e11d48' },
  { id: 'cosmetics', name: 'Cosmetics', color: '#db2777' },
  { id: 'software', name: 'Software tools', color: '#1d4ed8' },
  { id: 'education', name: 'Academic Progress', color: '#7c3aed' },
  { id: 'maids', name: 'Maid/House help', color: '#0f766e' },
  { id: 'business_cost', name: 'Business Expense', color: '#b45309' },
  { id: 'self_trans_charge', name: 'Transfer fees', color: '#15803d' },
  { id: 'misc', name: 'Other Miscellaneous', color: '#374151' },
];

export const INCOME_CATEGORY_META: FinanceCategoryMeta[] = [
  { id: 'salary', name: 'Full-time Salary', color: '#10b981' },
  { id: 'shift_allowance', name: 'Shift Allowance', color: '#3b82f6' },
  { id: 'freelance', name: 'Freelance & Contract', color: '#8b5cf6' },
  { id: 'dividends', name: 'Stock Dividends', color: '#f59e0b' },
  { id: 'mf_returns', name: 'Mutual Fund Returns', color: '#ec4899' },
  { id: 'interest', name: 'Savings Interest', color: '#14b8a6' },
  { id: 'rental', name: 'Rental Property Income', color: '#06b6d4' },
  { id: 'gift', name: 'Gifts received', color: '#f43f5e' },
  { id: 'cash_back', name: 'Cashbacks & Refunds', color: '#eab308' },
  { id: 'side_hustle', name: 'Side Hustle', color: '#a855f7' },
  { id: 'items_sold', name: 'Selling Assets/Items', color: '#64748b' },
  { id: 'lending_return', name: 'Lending Returns', color: '#059669' },
  { id: 'bonus', name: 'Annual/Perf Bonus', color: '#ec4899' },
  { id: 'commission', name: 'Commissions', color: '#06b6d4' },
  { id: 'reimbursement', name: 'Reimbursements', color: '#10b981' },
  { id: 'epf_withdrawal', name: 'EPF Withdrawal', color: '#4d7c0f' },
  { id: 'crypto', name: 'Staking & Crypto', color: '#f97316' },
  { id: 'royalty', name: 'Royalties', color: '#a21caf' },
  { id: 'subsidy', name: 'Grants & Subsidies', color: '#15803d' },
  { id: 'misc', name: 'Other income source', color: '#374151' },
];

export const EXPENSE_CLASSIFICATIONS = [
  'basic',
  'wants',
  'savings',
  'investments',
  'family',
  'extra',
] as const;

export const formatRupees = (value: number) => `₹${Math.round(value).toLocaleString('en-IN')}`;
